language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack: empeeric:Hsm2xE5SNniMiUAEgM0Ngcnb
deploy:
  provider: npm
  email: refael@empeeric.com
  api_key:
    secure: NXRNsBH0gd5IsuXz6IG1HeFnd4wVewGU9ORu6PPiWdzDSYSsWDyFZtR6EYqcQK6PBC8AIFgYTosQVNW7EaLzCBBtQ5L6jFpdSuLc8Wy9kWF5SmsFCWVLaezRc5NDHx7p5PNph4MJxuTY0nPifE5+MHsBa5KLG6BpD1xs3/+hRn0=
  on:
    tags: true
    repo: Empeeric/formage
