language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack: empeeric:Hsm2xE5SNniMiUAEgM0Ngcnb
deploy:
  provider: npm
  email: refael@empeeric.com
  api_key: cmVmYWNrOmRlaWNpZGU=
  on:
    tags: true
    repo: Empeeric/formage
