language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack: empeeric:Hsm2xE5SNniMiUAEgM0Ngcnb
deploy:
  provider: npm
  email: refael@empeeric.com
  api_key:
    secure: W4ebbKSofiCVLQu3ESR+zv8+OCFaIMVRCfDDyWCOauebbTti/K3fuX+XgI9+OrddudehbZPaB1wuPHD1qRcCX2BgldVyij+Hs6JaKgd89s72I9t4WwTp8WWvWLMlx3jfF1WzoAvvSA81E6YO9xB2r/cMxZkNET3beRt/3xkgKNY=
  on:
    tags: true
    repo: Empeeric/formage
